from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class SearchCatalogEntry:
    symbol: str
    name: str
    aliases: tuple[str, ...] = ()


DEFAULT_SEARCH_CATALOG: tuple[SearchCatalogEntry, ...] = (
    # Core mega caps and platform names
    SearchCatalogEntry("AAPL", "Apple Inc", ("apple",)),
    SearchCatalogEntry("MSFT", "Microsoft Corporation", ("microsoft",)),
    SearchCatalogEntry("NVDA", "NVIDIA Corporation", ("nvidia",)),
    SearchCatalogEntry("AMZN", "Amazon.com Inc", ("amazon",)),
    SearchCatalogEntry("GOOGL", "Alphabet Inc Class A", ("google", "alphabet",)),
    SearchCatalogEntry("GOOG", "Alphabet Inc Class C", ("google", "alphabet",)),
    SearchCatalogEntry("META", "Meta Platforms Inc", ("facebook", "meta",)),
    SearchCatalogEntry("TSLA", "Tesla Inc", ("tesla",)),
    SearchCatalogEntry("BRK-B", "Berkshire Hathaway Inc Class B", ("berkshire", "warren buffett")),
    SearchCatalogEntry("AVGO", "Broadcom Inc", ("broadcom",)),
    SearchCatalogEntry("ORCL", "Oracle Corporation", ("oracle",)),
    SearchCatalogEntry("NFLX", "Netflix Inc", ("netflix",)),
    SearchCatalogEntry("AMD", "Advanced Micro Devices Inc", ("amd", "advanced micro devices")),
    SearchCatalogEntry("INTC", "Intel Corporation", ("intel",)),
    SearchCatalogEntry("QCOM", "QUALCOMM Incorporated", ("qualcomm",)),
    SearchCatalogEntry("TXN", "Texas Instruments Incorporated", ("texas instruments",)),
    SearchCatalogEntry("CSCO", "Cisco Systems Inc", ("cisco",)),
    SearchCatalogEntry("IBM", "International Business Machines Corporation", ("ibm",)),
    SearchCatalogEntry("ADBE", "Adobe Inc", ("adobe",)),
    SearchCatalogEntry("CRM", "Salesforce Inc", ("salesforce",)),
    SearchCatalogEntry("NOW", "ServiceNow Inc", ("servicenow",)),
    SearchCatalogEntry("SNOW", "Snowflake Inc", ("snowflake",)),
    SearchCatalogEntry("PLTR", "Palantir Technologies Inc", ("palantir",)),
    SearchCatalogEntry("SHOP", "Shopify Inc", ("shopify",)),
    SearchCatalogEntry("PANW", "Palo Alto Networks Inc", ("palo alto networks",)),
    SearchCatalogEntry("CRWD", "CrowdStrike Holdings Inc", ("crowdstrike",)),
    SearchCatalogEntry("ZS", "Zscaler Inc", ("zscaler",)),
    SearchCatalogEntry("DDOG", "Datadog Inc", ("datadog",)),
    SearchCatalogEntry("MDB", "MongoDB Inc", ("mongodb",)),
    SearchCatalogEntry("TEAM", "Atlassian Corporation", ("atlassian",)),
    SearchCatalogEntry("UBER", "Uber Technologies Inc", ("uber",)),
    SearchCatalogEntry("ABNB", "Airbnb Inc", ("airbnb",)),
    SearchCatalogEntry("PYPL", "PayPal Holdings Inc", ("paypal",)),
    SearchCatalogEntry("COIN", "Coinbase Global Inc", ("coinbase", "crypto exchange", "co")),
    SearchCatalogEntry("HOOD", "Robinhood Markets Inc", ("robinhood",)),
    SearchCatalogEntry("SOFI", "SoFi Technologies Inc", ("sofi",)),
    SearchCatalogEntry("ARM", "Arm Holdings plc", ("arm holdings",)),

    # Semiconductors and infrastructure
    SearchCatalogEntry("AMAT", "Applied Materials Inc", ("applied materials",)),
    SearchCatalogEntry("LRCX", "Lam Research Corporation", ("lam research",)),
    SearchCatalogEntry("KLAC", "KLA Corporation", ("kla",)),
    SearchCatalogEntry("MU", "Micron Technology Inc", ("micron",)),
    SearchCatalogEntry("MRVL", "Marvell Technology Inc", ("marvell",)),
    SearchCatalogEntry("ADI", "Analog Devices Inc", ("analog devices",)),
    SearchCatalogEntry("MCHP", "Microchip Technology Inc", ("microchip",)),
    SearchCatalogEntry("ANET", "Arista Networks Inc", ("arista",)),
    SearchCatalogEntry("DELL", "Dell Technologies Inc", ("dell",)),
    SearchCatalogEntry("SMCI", "Super Micro Computer Inc", ("super micro", "supermicro")),

    # Consumer, media, telecom
    SearchCatalogEntry("KO", "The Coca-Cola Company", ("coca cola", "coca-cola", "coke", "co")),
    SearchCatalogEntry("PEP", "PepsiCo Inc", ("pepsico", "pepsi")),
    SearchCatalogEntry("MCD", "McDonalds Corporation", ("mcdonalds",)),
    SearchCatalogEntry("SBUX", "Starbucks Corporation", ("starbucks",)),
    SearchCatalogEntry("NKE", "NIKE Inc", ("nike",)),
    SearchCatalogEntry("DIS", "The Walt Disney Company", ("disney",)),
    SearchCatalogEntry("CMCSA", "Comcast Corporation", ("comcast",)),
    SearchCatalogEntry("T", "AT&T Inc", ("att", "at&t")),
    SearchCatalogEntry("VZ", "Verizon Communications Inc", ("verizon",)),
    SearchCatalogEntry("TMUS", "T-Mobile US Inc", ("t mobile", "tmobile")),
    SearchCatalogEntry("BKNG", "Booking Holdings Inc", ("booking",)),
    SearchCatalogEntry("MAR", "Marriott International Inc", ("marriott",)),
    SearchCatalogEntry("HLT", "Hilton Worldwide Holdings Inc", ("hilton",)),
    SearchCatalogEntry("RCL", "Royal Caribbean Cruises Ltd", ("royal caribbean",)),
    SearchCatalogEntry("CCL", "Carnival Corporation", ("carnival",)),
    SearchCatalogEntry("NCLH", "Norwegian Cruise Line Holdings Ltd", ("norwegian cruise",)),
    SearchCatalogEntry("SPOT", "Spotify Technology SA", ("spotify",)),

    # Retail and consumer staples
    SearchCatalogEntry("WMT", "Walmart Inc", ("walmart",)),
    SearchCatalogEntry("COST", "Costco Wholesale Corporation", ("costco",)),
    SearchCatalogEntry("HD", "The Home Depot Inc", ("home depot",)),
    SearchCatalogEntry("LOW", "Lowes Companies Inc", ("lowes",)),
    SearchCatalogEntry("TGT", "Target Corporation", ("target",)),
    SearchCatalogEntry("DG", "Dollar General Corporation", ("dollar general",)),
    SearchCatalogEntry("DLTR", "Dollar Tree Inc", ("dollar tree",)),
    SearchCatalogEntry("ROST", "Ross Stores Inc", ("ross stores",)),
    SearchCatalogEntry("TJX", "The TJX Companies Inc", ("tjx", "tj maxx")),
    SearchCatalogEntry("WBA", "Walgreens Boots Alliance Inc", ("walgreens",)),
    SearchCatalogEntry("CVS", "CVS Health Corporation", ("cvs",)),

    # Financials
    SearchCatalogEntry("JPM", "JPMorgan Chase & Co", ("jpmorgan", "jp morgan")),
    SearchCatalogEntry("BAC", "Bank of America Corporation", ("bank of america",)),
    SearchCatalogEntry("WFC", "Wells Fargo & Company", ("wells fargo",)),
    SearchCatalogEntry("C", "Citigroup Inc", ("citigroup", "citi")),
    SearchCatalogEntry("GS", "The Goldman Sachs Group Inc", ("goldman sachs",)),
    SearchCatalogEntry("MS", "Morgan Stanley", ("morgan stanley",)),
    SearchCatalogEntry("BLK", "BlackRock Inc", ("blackrock",)),
    SearchCatalogEntry("BX", "Blackstone Inc", ("blackstone",)),
    SearchCatalogEntry("KKR", "KKR & Co Inc", ("kkr",)),
    SearchCatalogEntry("SCHW", "The Charles Schwab Corporation", ("charles schwab", "schwab")),
    SearchCatalogEntry("AXP", "American Express Company", ("american express",)),
    SearchCatalogEntry("COF", "Capital One Financial Corporation", ("capital one",)),
    SearchCatalogEntry("V", "Visa Inc", ("visa",)),
    SearchCatalogEntry("MA", "Mastercard Incorporated", ("mastercard",)),
    SearchCatalogEntry("ICE", "Intercontinental Exchange Inc", ("ice", "intercontinental exchange")),
    SearchCatalogEntry("CME", "CME Group Inc", ("cme", "cme group")),
    SearchCatalogEntry("SPGI", "S&P Global Inc", ("s&p global", "sp global", "ratings")),

    # Healthcare and biotech
    SearchCatalogEntry("LLY", "Eli Lilly and Company", ("eli lilly", "lilly")),
    SearchCatalogEntry("JNJ", "Johnson & Johnson", ("johnson and johnson",)),
    SearchCatalogEntry("UNH", "UnitedHealth Group Incorporated", ("unitedhealth",)),
    SearchCatalogEntry("MRK", "Merck & Co Inc", ("merck",)),
    SearchCatalogEntry("ABBV", "AbbVie Inc", ("abbvie",)),
    SearchCatalogEntry("PFE", "Pfizer Inc", ("pfizer",)),
    SearchCatalogEntry("AMGN", "Amgen Inc", ("amgen",)),
    SearchCatalogEntry("BMY", "Bristol-Myers Squibb Company", ("bristol myers",)),
    SearchCatalogEntry("GILD", "Gilead Sciences Inc", ("gilead",)),
    SearchCatalogEntry("ABT", "Abbott Laboratories", ("abbott",)),
    SearchCatalogEntry("TMO", "Thermo Fisher Scientific Inc", ("thermo fisher",)),
    SearchCatalogEntry("DHR", "Danaher Corporation", ("danaher",)),
    SearchCatalogEntry("SYK", "Stryker Corporation", ("stryker",)),
    SearchCatalogEntry("ISRG", "Intuitive Surgical Inc", ("intuitive surgical",)),
    SearchCatalogEntry("VRTX", "Vertex Pharmaceuticals Incorporated", ("vertex",)),
    SearchCatalogEntry("REGN", "Regeneron Pharmaceuticals Inc", ("regeneron",)),
    SearchCatalogEntry("ELV", "Elevance Health Inc", ("elevance", "anthem")),
    SearchCatalogEntry("MDT", "Medtronic plc", ("medtronic",)),

    # Industrials and transport
    SearchCatalogEntry("CAT", "Caterpillar Inc", ("caterpillar",)),
    SearchCatalogEntry("DE", "Deere & Company", ("deere", "john deere")),
    SearchCatalogEntry("GE", "GE Aerospace", ("general electric", "ge aerospace")),
    SearchCatalogEntry("HON", "Honeywell International Inc", ("honeywell",)),
    SearchCatalogEntry("RTX", "RTX Corporation", ("raytheon", "rtx")),
    SearchCatalogEntry("LMT", "Lockheed Martin Corporation", ("lockheed martin",)),
    SearchCatalogEntry("NOC", "Northrop Grumman Corporation", ("northrop grumman",)),
    SearchCatalogEntry("BA", "The Boeing Company", ("boeing",)),
    SearchCatalogEntry("UPS", "United Parcel Service Inc", ("ups",)),
    SearchCatalogEntry("FDX", "FedEx Corporation", ("fedex",)),
    SearchCatalogEntry("UNP", "Union Pacific Corporation", ("union pacific",)),
    SearchCatalogEntry("NSC", "Norfolk Southern Corporation", ("norfolk southern",)),
    SearchCatalogEntry("ADP", "Automatic Data Processing Inc", ("adp",)),
    SearchCatalogEntry("ETN", "Eaton Corporation plc", ("eaton",)),
    SearchCatalogEntry("PH", "Parker-Hannifin Corporation", ("parker hannifin",)),
    SearchCatalogEntry("EMR", "Emerson Electric Co", ("emerson electric",)),

    # Energy, utilities, materials
    SearchCatalogEntry("XOM", "Exxon Mobil Corporation", ("exxon", "exxon mobil")),
    SearchCatalogEntry("CVX", "Chevron Corporation", ("chevron",)),
    SearchCatalogEntry("COP", "ConocoPhillips", ("conocophillips",)),
    SearchCatalogEntry("OXY", "Occidental Petroleum Corporation", ("occidental",)),
    SearchCatalogEntry("SLB", "Schlumberger NV", ("schlumberger",)),
    SearchCatalogEntry("EOG", "EOG Resources Inc", ("eog resources",)),
    SearchCatalogEntry("MPC", "Marathon Petroleum Corporation", ("marathon petroleum",)),
    SearchCatalogEntry("PSX", "Phillips 66", ("phillips 66",)),
    SearchCatalogEntry("NEE", "NextEra Energy Inc", ("nextera",)),
    SearchCatalogEntry("DUK", "Duke Energy Corporation", ("duke energy",)),
    SearchCatalogEntry("SO", "The Southern Company", ("southern company",)),
    SearchCatalogEntry("LIN", "Linde plc", ("linde",)),
    SearchCatalogEntry("APD", "Air Products and Chemicals Inc", ("air products",)),
    SearchCatalogEntry("NEM", "Newmont Corporation", ("newmont", "gold miner")),
    SearchCatalogEntry("FCX", "Freeport-McMoRan Inc", ("freeport",)),

    # Broad-market, sector and thematic ETFs
    SearchCatalogEntry("SPY", "SPDR S&P 500 ETF Trust", ("s&p 500", "sp500", "sp 500", "sp", "spy")),
    SearchCatalogEntry("VOO", "Vanguard S&P 500 ETF", ("s&p 500", "sp500", "sp 500", "index etf")),
    SearchCatalogEntry("IVV", "iShares Core S&P 500 ETF", ("s&p 500", "sp500", "sp 500", "core etf")),
    SearchCatalogEntry("SPLG", "SPDR Portfolio S&P 500 ETF", ("s&p 500", "sp500", "sp")),
    SearchCatalogEntry("QQQ", "Invesco QQQ Trust", ("nasdaq", "nasdaq 100")),
    SearchCatalogEntry("DIA", "SPDR Dow Jones Industrial Average ETF Trust", ("dow", "dow jones")),
    SearchCatalogEntry("IWM", "iShares Russell 2000 ETF", ("russell 2000", "small cap")),
    SearchCatalogEntry("VTI", "Vanguard Total Stock Market ETF", ("total stock market", "core etf")),
    SearchCatalogEntry("VT", "Vanguard Total World Stock ETF", ("total world", "world etf")),
    SearchCatalogEntry("VEA", "Vanguard FTSE Developed Markets ETF", ("developed markets",)),
    SearchCatalogEntry("VXUS", "Vanguard Total International Stock ETF", ("international stock", "core etf")),
    SearchCatalogEntry("EFA", "iShares MSCI EAFE ETF", ("developed markets", "international etf")),
    SearchCatalogEntry("EEM", "iShares MSCI Emerging Markets ETF", ("emerging markets",)),
    SearchCatalogEntry("SCHD", "Schwab U.S. Dividend Equity ETF", ("dividend etf",)),
    SearchCatalogEntry("VIG", "Vanguard Dividend Appreciation ETF", ("dividend", "quality dividend")),
    SearchCatalogEntry("DGRO", "iShares Core Dividend Growth ETF", ("dividend growth",)),
    SearchCatalogEntry("XLK", "Technology Select Sector SPDR Fund", ("technology etf", "tech etf")),
    SearchCatalogEntry("XLF", "Financial Select Sector SPDR Fund", ("financial etf", "banks etf")),
    SearchCatalogEntry("XLV", "Health Care Select Sector SPDR Fund", ("healthcare etf",)),
    SearchCatalogEntry("XLE", "Energy Select Sector SPDR Fund", ("energy etf",)),
    SearchCatalogEntry("XLI", "Industrial Select Sector SPDR Fund", ("industrials etf",)),
    SearchCatalogEntry("XLP", "Consumer Staples Select Sector SPDR Fund", ("consumer staples etf",)),
    SearchCatalogEntry("XLY", "Consumer Discretionary Select Sector SPDR Fund", ("consumer discretionary etf",)),
    SearchCatalogEntry("XLU", "Utilities Select Sector SPDR Fund", ("utilities etf",)),
    SearchCatalogEntry("SMH", "VanEck Semiconductor ETF", ("semiconductor etf", "chip etf")),
    SearchCatalogEntry("SOXX", "iShares Semiconductor ETF", ("semiconductor etf", "chip etf")),
    SearchCatalogEntry("XBI", "SPDR S&P Biotech ETF", ("biotech etf",)),
    SearchCatalogEntry("XHB", "SPDR S&P Homebuilders ETF", ("homebuilders etf",)),
    SearchCatalogEntry("XRT", "SPDR S&P Retail ETF", ("retail etf",)),
    SearchCatalogEntry("GLD", "SPDR Gold Shares", ("gold etf", "gold")),
    SearchCatalogEntry("SLV", "iShares Silver Trust", ("silver etf", "silver")),
    SearchCatalogEntry("TLT", "iShares 20+ Year Treasury Bond ETF", ("treasury etf", "bonds")),
    SearchCatalogEntry("BND", "Vanguard Total Bond Market ETF", ("bond etf", "bonds")),
    SearchCatalogEntry("HYG", "iShares iBoxx High Yield Corporate Bond ETF", ("high yield bond",)),
    SearchCatalogEntry("ARKK", "ARK Innovation ETF", ("ark innovation", "innovation etf")),
    SearchCatalogEntry("IWF", "iShares Russell 1000 Growth ETF", ("growth etf",)),
    SearchCatalogEntry("IWD", "iShares Russell 1000 Value ETF", ("value etf",)),
)
